default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: spablog
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: spablog_dev

test:
  <<: *default
  database: spablog_test

production:
  <<: *default
  database: spablog
